### ISSUE TITLE
Build is broken due to gwihlidal/ k-mem-rs#54

### ISSUE THREAD

**Issue by MatthewBlanchard** [aclysma/skulpin#101]
Won't build because the Ash APi changed.

**Comment by aclysma** [comment]
Thanks for letting me know. Rafx 0.0.14 removed vk-mem for a pure rust impl. I can update that some time this week. If you want to try to do it locally to unblock yourself now, bump the version and rebuild the shader.

**Comment by aclysma** [comment]
Published 0.14.1 which removes vk-mem-rs as a dependency
