### ISSUE TITLE
Rust version requirement?

### ISSUE THREAD

**Issue by canadaduane** [aclysma/skulpin#11]
When attempting to install and run the interactive example, I see many errors such as:

```
error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> C:\Users\Johnsons\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha4\src\platform_impl\windows\event_loop.rs:1736:46
     |
1736 |                                     pen_info.as_mut_ptr(),
     |                                              ^^^^^^^^^^
```

Does skulpin require nightly rustc?

**Comment by aclysma** [comment]
I'm not sure what minimum Rust version is required, but I believe MaybeUninit was stabilized in 1.36. CI is successfully building against stable, beta and nightly. (https://travis-ci.org/aclysma/skulpin)

**Comment by aclysma** [comment]
I looked into this a bit. What was checked in before required 1.38.0. I was able to make a simple change to get the minimum required version down to 1.36.0. `winit` requires 1.36.0 for MaybeUninit support, so this project's minimum required version will be 1.36 for now.

I've added 1.36.0 to the CI config and a note about this to the readme.
