### ISSUE TITLE
Crash on startup (Windows 10)

### ISSUE THREAD

**Issue by canadaduane** [aclysma/skulpin#12]
I tried running the example on Windows 10, but my entire screen went black, the app crashed, and my powershell was left unresponsive (but I was able to force close it!)

Steps to reproduce:
1. Install rust
2. Use nightly rust (`rustup default nightly`)
3. Install LunarG Vulkan (https://vulkan.lunarg.com/sdk/home#windows)
4. Run `cargo run --example interactive`

After compiling all of the dependencies, a window starts for skulpin but remains blank. It is also unresponsive to events. Then it takes control of the entire screen (not just the window) and things go black. Then windows recovers, kills the process, and powershell window from whence skulpin started is left blank / unable to render / unresponsive.

Whew! These are the scars of early adoption, but I'm sure it'll be worth it in the end :)

**Comment by aclysma** [comment]
The examples don't go full screen, so if you had the screen go blank, I suspect that you had a driver crash. What GPU are you running and how recently have you updated your drivers? There should be some good info in DxDiag. Unfortunately this is likely something that can only be reproduced with certain combinations of GPU and driver versions. Thanks for taking the time to report this!

**Comment by canadaduane** [comment]
I'm using a 1080ti with fairly recent drivers (within the last 6 months). I
didn't know about DxDiag.exe. I'll open it up next time.

**Comment by aclysma** [comment]
Would it be possible to give this another try with latest code? I put in a few fixes that might do some good. If it still doesn't work, pasting the log would be really helpful.

**Comment by canadaduane** [comment]
It's working! I did a `git pull` and then re-tried the `cargo run --example interactive` and it was good to go. Thanks for the fix.

**Comment by aclysma** [comment]
Nice! Glad to hear :)
