### ISSUE TITLE
Expose method to choose the present mode (i.e. FIFO, MAILBOX, etc.)

### ISSUE THREAD

**Issue by aclysma** [aclysma/skulpin#22]
I think some people will prefer FIFO since it's locked to vsync and doesn't render any more than necessary, but others might prefer MAILBOX for its lower latency. This is something that should be configurable.

- [x] Expose functionality to choose the present mode
- [x] Document in code
- [x] Document in README

**Comment by aclysma** [comment]
Implemented, but should hold off on closing until it's better documented in comments and possibly in the README

**Comment by kotx** [comment]
Is this no longer supported? For some reason setting `vsync_enabled(false)` in `RendererBuilder` sets the present mode to FIFO_RELAXED instead of MAILBOX. Unclear if this is a bug, which is why I'm asking here.
