### ISSUE TITLE
Demo drawing with WASM Skia bindings

### ISSUE THREAD

**Issue by aclysma** [aclysma/skulpin#28]
It may be possible to load and render a WASM module. This could allow for fast iteration times and usage from languages other than Rust.

**Comment by mankinskin** [comment]
I would very much enjoy being able to use skulpin in web pages. I am just stopping by but I am very interested in GPU accelerated web graphics with WASM, Vulkan and Rust. Is it possible to compile a skuplin app to wasm and run it in the browser with GPU rendering?

**Comment by aclysma** [comment]
There are a number of issues with running in a browser:
 - skia is a huge c++ library
 - vulkan is not safe to expose in a browser

When I was exploring this I was looking more at using web assembly as a lightweight reloadable bit of logic to decide what to draw in a native application. (Kind of like how flutter uses dart). Accepting a wasm module would allow skulpin to be used from other languages. But based on playing with it, the wasm runtimes available look like they still need some work. But it’s very promising!

**Comment by aclysma** [comment]
Closing, not likely to be taken up in the future.
