### ISSUE TITLE
Use in some GUI framework like qt

### ISSUE THREAD

**Issue by happydpc** [aclysma/skulpin#33]
I would like to embed this framework with some real applications by qt. Hope someday this can work with external gui framework.

**Comment by aclysma** [comment]
You might be able to get something going using Skia and QT directly.. this example is in C++ but I imagine the general approach would still work: https://github.com/zub2/SkiaExample

**Comment by happydpc** [comment]
Ok, thanks, I will try to make it to rust.

**Comment by aclysma** [comment]
Going to close this, I think for now QT integration is a bit outside the scope of this project.
