### ISSUE TITLE
Build errors with ash 0.30

### ISSUE THREAD

**Issue by msiglreith** [aclysma/skulpin#44]
The crates seem to specify dependencies via `>=`, which causes issues for breaking changes.

**Comment by aclysma** [comment]
As a workaround you can run this command:
`cargo update -p ash:0.30.0 --precise 0.29`

I was expecting that you could put ash = "0.29" in your own cargo.toml and cargo would be smart enough to figure out that 0.29 was the latest version that satisfied the requirements for all dependencies and just use 0.29 everywhere. I was leaving it open-ended with the hope that if ash made minor updates the library could accommodate people on different versions. (For example AFAIK skulpin works fine with winit 0.21, 0.22, and 0.23, and it works with many versions of skia_safe.) I'll have to ask around what the best practice is here.

**Comment by aclysma** [comment]
(Also since ash 0.30 is definitely not compatible, I'd like to publish a skulpin 0.8.2 that restricts this to ash 0.29 and then fix it to work with ash 0.30 and publish that as skulpin 0.9)

**Comment by aclysma** [comment]
For now I've pushed skulpin 0.8.2 which fixes the build error with as 0.29 and skulpin 0.9.0 which uses ash 0.30 and a more recent minimum version of skia_safe. Features had been changed on skia_safe so it was good to pick those changes up as well.

**Comment by msiglreith** [comment]
Thanks, runs smoothly! (:
