### ISSUE TITLE
VkError(ERROR_LAYER_NOT_PRESENT) when running examples.

### ISSUE THREAD

**Issue by FrankenApps** [aclysma/skulpin#58]
When I try to run any example, I get this error after the first frame:
`Error during renderer construction: CreateInstanceError(InstanceError(VkError(ERROR_LAYER_NOT_PRESENT)))`
I try to run the examples on a Windows 10 machine with MSVC. 

`vkcube` works without any issues.

**Comment by aclysma** [comment]
Sounds like the vulkan SDK isn't installed - have you tried that yet? Alternatively you can disable the debug layer in the example. (see also #54)

Requirements for windows: https://github.com/aclysma/skulpin#windows

**Comment by FrankenApps** [comment]
Well, I have installed it. Not sure how to test tough (I thought beeing able to run `vkcube` is sufficient)...
Your method of disabling the debug layer works great however.

**Comment by aclysma** [comment]
You could try running vulkaninfo, windows instructions are at the bottom here:
https://vulkan.lunarg.com/doc/view/1.2.141.2/windows/vulkaninfo.html

I think it will show all the layers that are available including the debug layer. This tool should be installed as part of the SDK. (Although I'm on macOS so can't confirm myself). I'm not sure how much help I'll be for it, but this would at least give you some more information to go off of.
