### ISSUE TITLE
objc 0.2.7 dependency fails to build

### ISSUE THREAD

**Issue by aclysma** [aclysma/skulpin#6]
The current workaround is to force cargo to use 0.2.6

`cargo update -p objc --precise 0.2.6`

**Comment by aclysma** [comment]
Found a better fix. Apparently specifying objc = "0.2.6" still permits upgrading to anything < 1.0.0. However a more explicit version requirement can be specified: objc = ">=0.2,<0.2.7"

This avoids users having to force updating to a particular version and for now builds out-of-the-box, but it may be worth asking the maintainer of objc if there is a better solution, and if this is a known problem.

**Comment by SSheldon** [comment]
@aclysma the `metal-rs` crate has been renamed to `metal`! The version of it and `cocoa` that you're using are a couple years old and unfortunately exercised the unsound behavior that is no longer allowed in objc 0.2.7, described in SSheldon/rust-objc#62.

If you switch to using the `metal` crate with a version 0.16 or higher (which accordingly uses `cocoa` 0.19), you will be able to use objc 0.2.7 and you'll be safe from this undefined behavior.

**Comment by aclysma** [comment]
Updated to use `metal` instead of `metal-rs` in https://github.com/aclysma/skulpin/commit/a080e49afc9b75e471fc9806811db9fccaeb1d17 and this fixed the build problem. Thanks so much for the help!
