### ISSUE TITLE
Why do I need to vendorize imgui_support.rs?

### ISSUE THREAD

**Issue by ctrlcctrlv** [aclysma/skulpin#64]
Why isn't it part of skulpin_plugin_imgui?

**Comment by aclysma** [comment]
It's a bit too opinionated. It loads specific font files, ranges of characters, and has an unsafe strategy dealing with imgui being "global" that not everyone will agree with.

BTW if you do use it, you may want to remove the gamma correction code. I noticed that it's incorrect for a number of my projects and should simply be removed. (like this: https://github.com/aclysma/imgui-inspect/commit/5598c08a14b920e9b3d0cb80dadfc668a3283929)

**Comment by ctrlcctrlv** [comment]
Thanks for the explanation and advice. I am using it yes, see mfeq/Qglif#3. :-)
