### ISSUE TITLE
glfw

### ISSUE THREAD

**Issue by uhuntu** [aclysma/skulpin#68]
Do you think about glfw ? 

Now skulpin supports winit and sdl2, but seems like both winit and sdl2 are lack on IME support on Windows, https://github.com/Kethku/neovide/issues/125

After reading the article here: https://discourse.libsdl.org/t/can-i-use-sdl-disable-windows-ime-and-ignore-other-input-at-the-same-time-without-hacks/24468

Seems that GLFW is much promising that figuring out IME issues. https://github.com/glfw/glfw/issues/41#issuecomment-160421273

**Comment by aclysma** [comment]
I think it would be similar code to the SDL2 compatibility crate but I’m not sure since I haven’t tried it.

**Comment by aclysma** [comment]
I added glfw support in this branch: https://github.com/aclysma/skulpin/tree/glfw

I'm going to hold off on dropping this into trunk. Not sure if I want to maintain a third backend or if feature flags could be done in a better way. (As it stands now, a default build would build winit, sdl2, and glfw, which seems excessive.)

**Comment by aclysma** [comment]
(Also, a lot of the changes in that branch aren't actually necessary to add glfw support to the existing code, and what's in the branch will work if you slightly modify the trait implementation to match what's in 0.10.0

**Comment by uhuntu** [comment]
Actually I was working on glfw on https://github.com/uhuntu/skulpin/tree/glfw recently, but I was struggling on how to manipulate glfw's create_window_surface and get_required_instance_extensions, but seems you have a better way to use ash_window. Anyway, it's awesome that you make it, can't wait to let @Kethku know it :)

**Comment by uhuntu** [comment]
![ezgif-1-8708a34ace6d](https://user-images.githubusercontent.com/4939569/93750920-d9250a80-fc2e-11ea-8166-be01ad1042dd.gif)

**Comment by uhuntu** [comment]
At least we prove it :)

**Comment by uhuntu** [comment]
https://github.com/uhuntu/neovide/tree/glfw is WIP

**Comment by Kethku** [comment]
Hey this is super exciting!

**Comment by aclysma** [comment]
I was going to PR this today but I noticed on further testing that on macOS resizing the window breaks it. This could be a simple problem but for now I'm going to hold off on further work with it. However if someone wants to pick up the work from the glfw branch and figure out what's going wrong, and if there is a use case that it can cover that SDL2/winit cannot, then I'd be happy to see it added.

**Comment by uhuntu** [comment]
It's sad that I do not have a mac install.

**Comment by Kethku** [comment]
Sorry for the delay in responding. I think glfw has the potential to solve some basic text input problems which winit and sdl2 don't get right. But I completely agree that this should not be your responsibility. If we go down that route I will help with the management of glfw upstream.

Unfortunately my ability to push this forward is blocked on my current rewrite which is taking a bit (as rewrites do haha).

**Comment by uhuntu** [comment]
https://github.com/Kethku/neovide/pull/383

**Comment by uhuntu** [comment]
I am thinking if we decided to choose winit https://github.com/Kethku/neovide/issues/384#issuecomment-708255251, then why we stick on glfw ? Even that I have a PR here https://github.com/Kethku/neovide/pull/383 to resolve Chinese input issue by winit. I am thinking to close this issue in this moment as bad mac support.
