### ISSUE TITLE
Physical to logical position conversion is forgot on some examples

### ISSUE THREAD

**Issue by baloone** [aclysma/skulpin#78]
When the system is scaled, the click position is not computed well (see attachement), I don't know if it is the same for other events.

![2020-10-30 14-17-51_Slomo](https://user-images.githubusercontent.com/12080132/97710116-9e2eb600-1abb-11eb-8445-cfdd47707ceb.gif)

**Comment by baloone** [comment]
This issue does not appear when using sdl since sdl seems to set the scale factor to 1

**Comment by baloone** [comment]
I think it is only a problem on some examples, we should replace the line 161 of interactive_winit_app by this code and it will fix this example
`let position : LogicalPosition<f64> = previous_click.position.to_logical(input_state.scale_factor());`

**Comment by aclysma** [comment]
Fixed with #79, thanks for the report!
