### ISSUE TITLE
Scale factor on windows with sdl2

### ISSUE THREAD

**Issue by baloone** [aclysma/skulpin#80]
As I mentioned it in #78, on windows, with sdl2 back-end,  the scale-factor is not computed well.
In consequence, the window is blurred compared to the winit window.
![bug_skulpin](https://user-images.githubusercontent.com/12080132/98565362-d13c2b00-22ad-11eb-8116-6a9208ec0a41.png)

**Comment by aclysma** [comment]
Thanks for the info, hoping to get time to try this over the weekend!

**Comment by aclysma** [comment]
I think this is a problem in SDL2. Winit internally calls GetDpiForWindow for "Windows 10 Anniversary Update (1607) or later." (See [winit]/src/platform_impl/windows/dpi.rs

It looks like SDL uses GetDpiForMonitor: https://github.com/spurious/SDL-mirror/blob/6197e7643a7d30f737b83f0acefd8a53f5c07c1e/src/video/windows/SDL_windowsvideo.c

Some discussion in SDL2:
https://bugzilla.libsdl.org/show_bug.cgi?id=3281#c12
https://discourse.libsdl.org/t/sdl-window-allow-highdpi-does-not-seem-to-work/26901/2

If you're desperate to have this working, the SDL2 crate build.rs has support for patching in changes to SDL2. It may also be possible to use direct windows API calls to get something working.

**Comment by aclysma** [comment]
Going to close this since it seems to be upstream.
