### ISSUE TITLE
M1 Macs don't seem to work correctly

### ISSUE THREAD

**Issue by Kethku** [aclysma/skulpin#82]
https://github.com/Kethku/neovide/issues/409

**Comment by Kethku** [comment]
Specifically looks like the skia build fails

**Comment by aclysma** [comment]
skulpin calls the rust functions exposed in skia-safe which in turn calls into skia C/C++ code. skia-safe/skia-bindings needs to make that code available to the linker - this is something that will need to be looked at upstream.
