### ISSUE TITLE
Update to skia-safe 0.37

### ISSUE THREAD

**Issue by ghost** [aclysma/skulpin#84]
`skia-safe` 0.37, released 2 days ago, has a few breaking changes that would cause building `skulpin-renderer` to fail.

Please update the `skia-safe` dependency to require `>=0.37` so users of `skulpin-renderer` doesn't get this issue.

**Comment by aclysma** [comment]
Thanks for mentioning this. I've published a 0.10.1 which limits skia-safe to <0.37 to fix the build errors (added constraints on a couple other crates as well). I think this is the closest I can stay to semver rules while also fixing the build.

Updating skia-safe to >= 0.37 will require a 0.11 for skulpin or additional feature flags to opt-into 0.37. I don't plan to release a non-patch update until I migrate skulpin to a new renderer that I've been working on (shouldn't be too far out.) If you *need* >=0.37 immediately, adding a "None" param as a second arg to the function call fixes the compile error.

**Comment by aclysma** [comment]
0.12 includes skia 0.38.1. 0.38.0 has a serious issue so we shouldn’t allow using it. While 0.37 would work, since I haven’t published anything with 0.37 as a dependency I went straight to 0.38.1
