### ISSUE TITLE
Allow to disable vsync (change swap interval)

### ISSUE THREAD

**Issue by liquidev** [aclysma/skulpin#88]
For desktop apps that don't rerender unless the user does some action (using winit's ControlFlow::Wait), I think it would be a pretty good idea to allow for rendering *immediately* after the event occurs rather than waiting for vertical sync. This could reduce input lag in these kinds of applications.

**Comment by aclysma** [comment]
This is controllable by present mode. This choice affects latency, but it also affects power usage and if screen tearing is possible. The next version of rafx does not have present mode exposed but does have a simple vsync bool.

**Comment by liquidev** [comment]
As far as I could tell skulpin doesn't use rafx?

**Comment by aclysma** [comment]
The next version of skulpin (in the use-rafx branch) will use rafx. (My previous message I meant to say "next version of *skulpin* does not have present mode" (because rafx does not expose it)

**Comment by ghost** [comment]
Is the vsync bool configurable yet?

**Comment by aclysma** [comment]
It's there in rafx but there wasn't exposed. I've added it and will publish 0.13.0 when it passes CI
