### ISSUE TITLE
SIGSEGV when resizing

### ISSUE THREAD

**Issue by UE2020** [aclysma/skulpin#91]
When running the `interactive_winit_app` example in release mode, the application quits with a SIGSEGV after resizing the window. I'm running Arch Linux, and I'm using Intel UHD Graphics 620.

**Comment by aclysma** [comment]
Do you have a log/stack trace? I don't run linux as a desktop so I can't do much more than look at a log/stack and make a guess. I tried running `interactive_winit_app` on 0.12.0 on Windows and macOS and didn't see this occur.

**Comment by aclysma** [comment]
Cannot resolve without more info, closing. If you have logs feel free to reopen.
