### ISSUE TITLE
Application crash on minimizing window

### ISSUE THREAD

**Issue by kotx** [aclysma/skulpin#92]
I'm using the winit-app example. The app crashes when the window is minimized.
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\toast\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\skulpin-renderer-0.13.0\src\skia_support.rs:137:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/aclysma/skulpin/blob/9b02a01f589f36bbf1e0e7400baccbe164e9c735/skulpin-renderer/src/skia_support.rs#L128-L137

**Comment by aclysma** [comment]
Fixed in this change: https://github.com/aclysma/skulpin/commit/c8440b2ba3b09a4c6741dd34b1f1b0f918e96e56

I'll publish it as 0.13.1 once it passes CI

**Comment by kotx** [comment]
Also, while this issue is still open, do you know if the console getting spammed with `rafx_api::extra::swapchain_helper: Swapchain is sub-optimal, rebuilding` is normal when a renderer-only window is minimized?

**Comment by aclysma** [comment]
Yeah, I've seen that before. I have a TODO in the code:

```
//TODO: This can occur persistently when the app is minimized, so ignore
// if the size has not changed. However, we could also consider adding
// a counter to limit the frequency. (A sensible case for this is
// resizing a window - to avoid rebuilding swapchain every frame during
// the resize.
```

I don't think it's actually rebuilding, the logging might be a bit misleading. Improving the logging or coming up with a better heuristic might be worthwhile. I think you can safely ignore and/or suppress the logging for this in the meantime.
