### ISSUE TITLE
Method for checking if previous frame has been submitted

### ISSUE THREAD

**Issue by ghost** [aclysma/skulpin#96]
I'm encountering a situation where some frames take longer than usual to render, and I end up calling `renderer.draw(...)` too often, which will block for around 16ms. I want to be able to know when to call `renderer.draw(...)` without blocking for that long, since I have code to run multiple times per `renderer.draw(...)` call, like game update routines and the such.

There is a function, named `wait_until_previous_frame_submitted` in `rafx-api`, which is called by the `draw` function in `skulpin-renderer`, where I think the blocking is coming from. Maybe you can turn this into a `is_previous_frame_submitted` that uses `try_recv()` instead of `recv()`?

https://github.com/aclysma/rafx/blob/b2a2f679bcec9499a59ab61c7f228998f247fb80/rafx-api/src/extra/swapchain_helper.rs#L300-L321

**Comment by aclysma** [comment]
This sounds odd to me. Are you sure it isn't blocking on acquiring the next swapchain image? If you have something that must never block for more than a vsync interval, it may be better to do it in another thread. Games generally don't run multiple updates per single draw.

**Comment by ghost** [comment]
I think it is actually blocking on acquiring the next swapchain image, if anything.

I already have game updates in another thread, sending back `SkPicture`s to draw as frames every 16ms, but I still do end up with a situation where some frames take a bit too long to be rendered, and subsequent frames have to be delayed/discarded, resulting in some latency.

I much prefer game updates to happen in the same thread and the program to only attempt to render when the next swapchain image is ready.

**Comment by aclysma** [comment]
It may be possible to render the frame independently of the swapchain (maybe more frequently than per-vsync) - so that once the swapchain image is available, you only need to do a single texture blit from the previous pre-rendered frame to the swapchain image. (Sounds like what you're already doing.)

More fine-grained control on the timing, and doing a non-blocking check for the swapchain image being ready is possible. There are a few APIs on the swapchain helper that would let you do more fine-grained checks. (wait_until_previous_frame_submitted, wait_until_sync_frame_idle) However, you may need to use vulkan fences directly. You might consider interacting with the swapchain object yourself instead of the swapchain helper. (It's set up for the simple case of blocking until a swapchain image is available before drawing the next frame.

**Comment by ghost** [comment]
> Sounds like what you're already doing.

Well actually not at all. Please allow me to explain again, bear with me for a second: I'm just using an MPSC channel to send instances `SkPicture`s (just the result of a virtual canvas that records Skia draw commands) from the game thread over to the main thread (the draw thread) once every 16ms (assuming 60fps), timed by the game thread itself.

That mechanism works well for splitting the draw thread and the main thread, but I do encounter a situation on the draw thread where it sometimes blocks (not just because of a frame taking too long to render, but also occurs on window resize, setting fullscreen, ect) and the MPSC channel gets full. This ends me up with some latency because the `SkPicture`s are created by the game thread earlier and only rendered & presented on the screen by the draw thread at a later time due to the blocking.

I came up with this weird multithreaded scheme because I initially wrote my game while Skulpin at that time would appear to have no upfront multithreading support, but now it no longer matters. We have a nice non-blocking swapchain to use, so I'd like to get rid of all the thread mess and use one thread only, but I will be needing something to check if it's okay to call `renderer.draw(...)` so it doesn't block, which brings me to the creation of this issue.

Sorry if I'm annoying you, I have no experience with graphics programming, and I used Skulpin as it seemed to be a convenient library for getting some stuff on screen.

> doing a non-blocking check for the swapchain image being ready is possible

Alright, I'll look around in the Skulpin & Rafx source code and see what I can already do. Hopefully I don't have to end up modifying/adding any more code.

**Comment by ghost** [comment]
Adding this function seems to work well (I should add that I'm using rafx-api v0.0.10, `git checkout v0.0.10` to match the Skulpin version I'm using):

```rust
// rafx-api/src/extra/swapchain_helper.rs
impl RafxSwapchainHelper {
    pub fn can_draw_without_blocking(&self) -> bool {
        // Is previous frame completed being submitted to GPU?
        let a = !self.shared_state.as_ref().unwrap().result_rx.is_empty();
        let next_sync_frame = self
            .shared_state
            .as_ref()
            .unwrap()
            .sync_frame_index
            .load(Ordering::Relaxed);
        let fs = self.shared_state.as_ref().unwrap().in_flight_fences[next_sync_frame].get_fence_status().unwrap();
        // Is next frame index done submitting?
        let b = fs != RafxFenceStatus::Incomplete;
        a && b
    }
}
```

The `self.shared_state.as_ref().unwrap().result_rx.is_empty()` is a bit problematic though, at startup it will always be `false`, so I have to call `renderer.draw(...) // draw nothing` once at app startup before using the function. Maybe I can fix that by keeping some extra state about whether we have fed something into the `result_tx` side, a bit crude but should work.

After messing around with some other related code, I found that the latency on my specific computer is _actually coming from here_, where (for some reason I'm not going to try to dig into, I'm tired today :P) removing `FifoRelaxed` from the present mode priority gets rid of the blocking.

```rust
// rafx-api/src/backends/vulkan/swapchain.rs line 72
const VSYNC_OFF_PRESENT_MODES: [VkPresentMode; 4] = [
    VkPresentMode::Mailbox,
    VkPresentMode::FifoRelaxed, // remove this, change array length to 3
    VkPresentMode::Immediate,
    VkPresentMode::Fifo,
];
```

Even though I'm sure that's where the latency is coming from now, I still think the `can_draw_without_blocking` function is useful, the code I have now makes use of it to ease the work of checking when to call it: I don't have to keep track of any timing myself.

**Comment by ghost** [comment]
Closing this, I'm using my own fork of skulpin instead. I'll do a PR of the function if I feel like it.
