### ISSUE TITLE
Reuse the last rendered frame for the next frame

### ISSUE THREAD

**Issue by Feuermagier** [aclysma/skulpin#97]
I'm writing a gui application using Skulpin and don't want to draw the whole gui every frame, but only the areas that changed since the last frame. When doing so, I experience heavy flickering (presumably because of double (or so) buffering, so every second frame has the old content still drawn on it). It would be great to have an option to reuse the last frame and draw with Skia on top of it, so you could just overwrite the areas that have changed and save cpu time as well as battery drain.

**Comment by aclysma** [comment]
I think it's a reasonable suggestion and would be happy to review a PR. However I don't plan to add any more features myself because I don't personally use this project anymore and have other projects I would rather work on.
