### ISSUE TITLE
What is the actual reason for this library now that the windowing support was removed?

### ISSUE THREAD

**Issue by ctrlcctrlv** [aclysma/skulpin#99]
The scope of this library has decreased a lot since its release.

It used to also handle windowing.

Now it pushes that off to winit or SDL2.

So, why should it even be used over `skia_safe::gpu::vk`?

**Comment by aclysma** [comment]
Being less coupled to SDL/winit makes this crate more flexible. It also means less breakage when those crates change. This crate was never intended to be a window manager.

Additionally, the vulkan code has been refactored into a separate crate (rafx), substantially reducing the amount of code in this crate.

This crate is targeted at prototyping/one-off visualization. I fully expect people to "outgrow" it and either fork just the bits they need or move to a more feature-rich framework. Now that it is a fraction of the size that it was, it's easier for someone to make that transition.

**Comment by ctrlcctrlv** [comment]
Thanks, I understand your goals better now :-)

You're definitely right that a shift to rust_skia's vk.rs was made a lot simpler by the recent changes, which is why I wondered.
